/* ──────────────────────────────────────────────────────
   Beyonders Wetland Module — Sample / Mock Data
   ────────────────────────────────────────────────────── */

import type {
  WetlandPulseData,
  WetlandPatch,
  SensitivityData,
  EvidenceCardData,
} from "./types";

/* ── Wetland Pulse ─────────────────────────────────── */

export const SAMPLE_PULSE: WetlandPulseData = {
  site: "Hakaluki Haor",
  wetland_area_km2: 54.0,
  dates: [
    { date: "2026-06-18", area_km2: 12.4, fraction: 0.23, mean_delta_db: 1.2, patches: 8 },
    { date: "2026-06-30", area_km2: 18.7, fraction: 0.35, mean_delta_db: 1.8, patches: 12 },
    { date: "2026-07-12", area_km2: 31.2, fraction: 0.58, mean_delta_db: 2.4, patches: 15 },
    { date: "2026-07-24", area_km2: 42.1, fraction: 0.78, mean_delta_db: 3.1, patches: 18 },
    { date: "2026-08-05", area_km2: 38.6, fraction: 0.72, mean_delta_db: 2.8, patches: 16 },
    { date: "2026-08-17", area_km2: 24.3, fraction: 0.45, mean_delta_db: 1.9, patches: 11 },
    { date: "2026-08-29", area_km2: 16.1, fraction: 0.30, mean_delta_db: 1.4, patches: 7 },
    { date: "2026-09-10", area_km2: 10.8, fraction: 0.20, mean_delta_db: 0.9, patches: 5 },
  ],
  onset: "2026-06-18",
  peak: { date: "2026-07-24", area_km2: 42.1 },
  recession_start: "2026-08-05",
};

/* ── Sample Patches ────────────────────────────────── */

export const SAMPLE_PATCHES: WetlandPatch[] = [
  {
    id: "wetland_patch_001",
    date: "2026-07-24",
    area_km2: 8.14,
    mean_delta_db: 3.42,
    median_delta_db: 3.18,
    valid_fraction: 0.94,
    vegetated_fraction: 0.12,
    classification: "OPEN_WATER",
    quality_status: "PASS",
    spatial_status: "PASS",
    temporal_status: "PASS",
    threshold_stability: "STABLE",
    evidence_state: "SUPPORTED",
    hh_before: -6.8,
    hh_after: -14.2,
    hv_before: -13.1,
    hv_after: -18.5,
    delta_hh: -7.4,
    delta_hv: -5.4,
    centroid: [24.635, 91.520],
  },
  {
    id: "wetland_patch_002",
    date: "2026-07-24",
    area_km2: 5.67,
    mean_delta_db: 2.87,
    median_delta_db: 2.61,
    valid_fraction: 0.91,
    vegetated_fraction: 0.73,
    classification: "VEGETATED_INUNDATION",
    quality_status: "PASS",
    spatial_status: "PASS",
    temporal_status: "PARTIAL",
    threshold_stability: "STABLE",
    evidence_state: "MODERATE",
    hh_before: -8.2,
    hh_after: -4.1,
    hv_before: -14.5,
    hv_after: -13.8,
    delta_hh: 4.1,
    delta_hv: 0.7,
    centroid: [24.610, 91.545],
  },
  {
    id: "wetland_patch_003",
    date: "2026-07-24",
    area_km2: 3.42,
    mean_delta_db: 2.18,
    median_delta_db: 1.94,
    valid_fraction: 0.88,
    vegetated_fraction: 0.67,
    classification: "VEGETATED_INUNDATION",
    quality_status: "PASS",
    spatial_status: "PASS",
    temporal_status: "PARTIAL",
    threshold_stability: "STABLE",
    evidence_state: "MODERATE",
    hh_before: -7.9,
    hh_after: -4.5,
    hv_before: -15.1,
    hv_after: -14.6,
    delta_hh: 3.4,
    delta_hv: 0.5,
    centroid: [24.650, 91.570],
  },
  {
    id: "wetland_patch_004",
    date: "2026-07-24",
    area_km2: 2.18,
    mean_delta_db: 1.73,
    median_delta_db: 1.52,
    valid_fraction: 0.79,
    vegetated_fraction: 0.41,
    classification: "UNCERTAIN",
    quality_status: "PASS",
    spatial_status: "PARTIAL",
    temporal_status: "PARTIAL",
    threshold_stability: "SENSITIVE",
    evidence_state: "UNCERTAIN",
    hh_before: -9.1,
    hh_after: -7.4,
    hv_before: -16.2,
    hv_after: -15.0,
    delta_hh: 1.7,
    delta_hv: 1.2,
    centroid: [24.590, 91.530],
  },
  {
    id: "wetland_patch_005",
    date: "2026-07-24",
    area_km2: 6.91,
    mean_delta_db: 3.84,
    median_delta_db: 3.67,
    valid_fraction: 0.96,
    vegetated_fraction: 0.08,
    classification: "OPEN_WATER",
    quality_status: "PASS",
    spatial_status: "PASS",
    temporal_status: "PASS",
    threshold_stability: "STABLE",
    evidence_state: "SUPPORTED",
    hh_before: -7.1,
    hh_after: -15.8,
    hv_before: -12.8,
    hv_after: -19.3,
    delta_hh: -8.7,
    delta_hv: -6.5,
    centroid: [24.625, 91.560],
  },
  {
    id: "wetland_patch_006",
    date: "2026-07-24",
    area_km2: 4.23,
    mean_delta_db: 2.56,
    median_delta_db: 2.31,
    valid_fraction: 0.85,
    vegetated_fraction: 0.82,
    classification: "VEGETATED_INUNDATION",
    quality_status: "PASS",
    spatial_status: "PASS",
    temporal_status: "PASS",
    threshold_stability: "STABLE",
    evidence_state: "SUPPORTED",
    hh_before: -8.6,
    hh_after: -5.2,
    hv_before: -14.9,
    hv_after: -14.3,
    delta_hh: 3.4,
    delta_hv: 0.6,
    centroid: [24.640, 91.505],
  },
  {
    id: "wetland_patch_007",
    date: "2026-07-24",
    area_km2: 1.45,
    mean_delta_db: 1.42,
    median_delta_db: 1.21,
    valid_fraction: 0.72,
    vegetated_fraction: 0.35,
    classification: "UNCERTAIN",
    quality_status: "PARTIAL",
    spatial_status: "PARTIAL",
    temporal_status: "PARTIAL",
    threshold_stability: "SENSITIVE",
    evidence_state: "UNCERTAIN",
    hh_before: -10.3,
    hh_after: -8.9,
    hv_before: -17.1,
    hv_after: -16.2,
    delta_hh: 1.4,
    delta_hv: 0.9,
    centroid: [24.665, 91.540],
  },
  {
    id: "wetland_patch_008",
    date: "2026-07-24",
    area_km2: 10.21,
    mean_delta_db: 4.12,
    median_delta_db: 3.94,
    valid_fraction: 0.97,
    vegetated_fraction: 0.05,
    classification: "OPEN_WATER",
    quality_status: "PASS",
    spatial_status: "PASS",
    temporal_status: "PASS",
    threshold_stability: "STABLE",
    evidence_state: "SUPPORTED",
    hh_before: -6.4,
    hh_after: -16.1,
    hv_before: -12.0,
    hv_after: -20.4,
    delta_hh: -9.7,
    delta_hv: -8.4,
    centroid: [24.600, 91.555],
  },
];

/* ── Sensitivity Data ──────────────────────────────── */

export const SAMPLE_SENSITIVITY: SensitivityData = {
  patch_id: "site_global",
  thresholds: [
    { delta_db: 0.5, area_km2: 48.3, patches: 42 },
    { delta_db: 1.0, area_km2: 43.1, patches: 35 },
    { delta_db: 1.5, area_km2: 41.6, patches: 31 },
    { delta_db: 2.0, area_km2: 40.2, patches: 28 },
    { delta_db: 2.5, area_km2: 39.8, patches: 26 },
    { delta_db: 3.0, area_km2: 38.4, patches: 24 },
    { delta_db: 3.5, area_km2: 32.1, patches: 19 },
    { delta_db: 4.0, area_km2: 22.7, patches: 12 },
    { delta_db: 4.5, area_km2: 12.2, patches: 6 },
    { delta_db: 5.0, area_km2: 4.8, patches: 3 },
  ],
  stability_verdict: "STABLE",
  stable_range: [1.0, 3.0],
  sensitivity_note: "Result remains within 12% for thresholds 1.0–3.0 dB",
};

/* ── Evidence Card ─────────────────────────────────── */

export const SAMPLE_EVIDENCE: EvidenceCardData = {
  region_id: "wetland_patch_002",
  region_name: "Patch 02 — SE Hakaluki",
  date: "24 Jul 2026",
  candidate_area_km2: 5.67,
  valid_fraction: 0.91,
  quality: "PASS",
  spatial_consistency: "PASS",
  temporal_evidence: "PARTIAL",
  threshold_stability: "STABLE",
  vegetated_signal: "POTENTIAL",
  evidence_strength: "MODERATE",
  provenance: {
    observed: ["HH backscatter", "HV backscatter", "Acquisition date", "Product metadata"],
    derived: ["ΔHH = 4.1 dB", "ΔHV = 0.7 dB", "Candidate area = 5.67 km²", "Expansion rate"],
    contextual: ["Wetland boundary (Hakaluki Haor)", "ESA WorldCover land cover"],
    potential: ["Vegetated inundation signal", "Double-bounce scattering hypothesis"],
  },
};
